source "http://www.rubygems.org"

gemspec

gem 'aws-sdk-v1',
    git: 'https://github.com/acquia/aws-sdk-ruby.git',
    branch: 'version-1-forward-compatibility'

group :test do
  gem "rspec", "2.14"
  gem "rake", "< 11.0"
  gem "factory_girl"
end
